# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.pheno_h2 <- function() {
    .Call(`_amsimr__pheno_h2`)
}

.pheno_comp_mean <- function(component_type) {
    .Call(`_amsimr__pheno_comp_mean`, component_type)
}

.pheno_comp_var <- function(component_type) {
    .Call(`_amsimr__pheno_comp_var`, component_type)
}

.pheno_comp_cor <- function(component_type) {
    .Call(`_amsimr__pheno_comp_cor`, component_type)
}

.pheno_comp_xcor <- function(component_type) {
    .Call(`_amsimr__pheno_comp_xcor`, component_type)
}

.pheno_latent_h2 <- function() {
    .Call(`_amsimr__pheno_latent_h2`)
}

.pheno_latent_comp_mean <- function(component_type) {
    .Call(`_amsimr__pheno_latent_comp_mean`, component_type)
}

.pheno_latent_comp_var <- function(component_type) {
    .Call(`_amsimr__pheno_latent_comp_var`, component_type)
}

.pheno_latent_comp_cor <- function(component_type) {
    .Call(`_amsimr__pheno_latent_comp_cor`, component_type)
}

.pheno_latent_comp_xcor <- function(component_type) {
    .Call(`_amsimr__pheno_latent_comp_xcor`, component_type)
}

.builder_new <- function() {
    .Call(`_amsimr__builder_new`)
}

