// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// _pheno_h2
SEXP _pheno_h2();
RcppExport SEXP _amsimr__pheno_h2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(_pheno_h2());
    return rcpp_result_gen;
END_RCPP
}
// _pheno_comp_mean
SEXP _pheno_comp_mean(std::string component_type);
RcppExport SEXP _amsimr__pheno_comp_mean(SEXP component_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type component_type(component_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(_pheno_comp_mean(component_type));
    return rcpp_result_gen;
END_RCPP
}
// _pheno_comp_var
SEXP _pheno_comp_var(std::string component_type);
RcppExport SEXP _amsimr__pheno_comp_var(SEXP component_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type component_type(component_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(_pheno_comp_var(component_type));
    return rcpp_result_gen;
END_RCPP
}
// _pheno_comp_cor
SEXP _pheno_comp_cor(std::string component_type);
RcppExport SEXP _amsimr__pheno_comp_cor(SEXP component_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type component_type(component_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(_pheno_comp_cor(component_type));
    return rcpp_result_gen;
END_RCPP
}
// _pheno_comp_xcor
SEXP _pheno_comp_xcor(std::string component_type);
RcppExport SEXP _amsimr__pheno_comp_xcor(SEXP component_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type component_type(component_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(_pheno_comp_xcor(component_type));
    return rcpp_result_gen;
END_RCPP
}
// _pheno_latent_h2
SEXP _pheno_latent_h2();
RcppExport SEXP _amsimr__pheno_latent_h2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(_pheno_latent_h2());
    return rcpp_result_gen;
END_RCPP
}
// _pheno_latent_comp_mean
SEXP _pheno_latent_comp_mean(std::string component_type);
RcppExport SEXP _amsimr__pheno_latent_comp_mean(SEXP component_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type component_type(component_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(_pheno_latent_comp_mean(component_type));
    return rcpp_result_gen;
END_RCPP
}
// _pheno_latent_comp_var
SEXP _pheno_latent_comp_var(std::string component_type);
RcppExport SEXP _amsimr__pheno_latent_comp_var(SEXP component_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type component_type(component_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(_pheno_latent_comp_var(component_type));
    return rcpp_result_gen;
END_RCPP
}
// _pheno_latent_comp_cor
SEXP _pheno_latent_comp_cor(std::string component_type);
RcppExport SEXP _amsimr__pheno_latent_comp_cor(SEXP component_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type component_type(component_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(_pheno_latent_comp_cor(component_type));
    return rcpp_result_gen;
END_RCPP
}
// _pheno_latent_comp_xcor
SEXP _pheno_latent_comp_xcor(std::string component_type);
RcppExport SEXP _amsimr__pheno_latent_comp_xcor(SEXP component_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type component_type(component_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(_pheno_latent_comp_xcor(component_type));
    return rcpp_result_gen;
END_RCPP
}
// _builder_new
SEXP _builder_new();
RcppExport SEXP _amsimr__builder_new() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(_builder_new());
    return rcpp_result_gen;
END_RCPP
}
// _builder_simulation
void _builder_simulation(SEXP sexp_builder, std::size_t n_generations, std::size_t n_individuals, std::string output_dir, std::uint64_t random_seed);
RcppExport SEXP _amsimr__builder_simulation(SEXP sexp_builderSEXP, SEXP n_generationsSEXP, SEXP n_individualsSEXP, SEXP output_dirSEXP, SEXP random_seedSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_builder(sexp_builderSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_generations(n_generationsSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_individuals(n_individualsSEXP);
    Rcpp::traits::input_parameter< std::string >::type output_dir(output_dirSEXP);
    Rcpp::traits::input_parameter< std::uint64_t >::type random_seed(random_seedSEXP);
    _builder_simulation(sexp_builder, n_generations, n_individuals, output_dir, random_seed);
    return R_NilValue;
END_RCPP
}
// _builder_genome
void _builder_genome(SEXP sexp_builder, std::size_t n_loci, std::vector<double> locus_mafs, std::vector<double> locus_recombination, std::vector<double> locus_mutation);
RcppExport SEXP _amsimr__builder_genome(SEXP sexp_builderSEXP, SEXP n_lociSEXP, SEXP locus_mafsSEXP, SEXP locus_recombinationSEXP, SEXP locus_mutationSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_builder(sexp_builderSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_loci(n_lociSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type locus_mafs(locus_mafsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type locus_recombination(locus_recombinationSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type locus_mutation(locus_mutationSEXP);
    _builder_genome(sexp_builder, n_loci, locus_mafs, locus_recombination, locus_mutation);
    return R_NilValue;
END_RCPP
}
// _builder_phenome
void _builder_phenome(SEXP sexp_builder, std::size_t n_phenotypes, std::vector<std::string> names, std::vector<std::size_t> loci, std::vector<double> h2_genetic, std::vector<double> h2_environmental, std::vector<double> h2_vertical, std::vector<double> genetic_cor, std::vector<double> environmental_cor);
RcppExport SEXP _amsimr__builder_phenome(SEXP sexp_builderSEXP, SEXP n_phenotypesSEXP, SEXP namesSEXP, SEXP lociSEXP, SEXP h2_geneticSEXP, SEXP h2_environmentalSEXP, SEXP h2_verticalSEXP, SEXP genetic_corSEXP, SEXP environmental_corSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_builder(sexp_builderSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type n_phenotypes(n_phenotypesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type names(namesSEXP);
    Rcpp::traits::input_parameter< std::vector<std::size_t> >::type loci(lociSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type h2_genetic(h2_geneticSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type h2_environmental(h2_environmentalSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type h2_vertical(h2_verticalSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type genetic_cor(genetic_corSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type environmental_cor(environmental_corSEXP);
    _builder_phenome(sexp_builder, n_phenotypes, names, loci, h2_genetic, h2_environmental, h2_vertical, genetic_cor, environmental_cor);
    return R_NilValue;
END_RCPP
}
// _builder_mating
void _builder_mating(SEXP sexp_builder, std::string mating_type, SEXP n_iterations, SEXP temp_init, SEXP temp_decay, SEXP mate_cor);
RcppExport SEXP _amsimr__builder_mating(SEXP sexp_builderSEXP, SEXP mating_typeSEXP, SEXP n_iterationsSEXP, SEXP temp_initSEXP, SEXP temp_decaySEXP, SEXP mate_corSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_builder(sexp_builderSEXP);
    Rcpp::traits::input_parameter< std::string >::type mating_type(mating_typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type temp_init(temp_initSEXP);
    Rcpp::traits::input_parameter< SEXP >::type temp_decay(temp_decaySEXP);
    Rcpp::traits::input_parameter< SEXP >::type mate_cor(mate_corSEXP);
    _builder_mating(sexp_builder, mating_type, n_iterations, temp_init, temp_decay, mate_cor);
    return R_NilValue;
END_RCPP
}
// _builder_metrics
void _builder_metrics(SEXP sexp_builder, Rcpp::List metrics);
RcppExport SEXP _amsimr__builder_metrics(SEXP sexp_builderSEXP, SEXP metricsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_builder(sexp_builderSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type metrics(metricsSEXP);
    _builder_metrics(sexp_builder, metrics);
    return R_NilValue;
END_RCPP
}
// _builder_build
SEXP _builder_build(SEXP sexp_builder);
RcppExport SEXP _amsimr__builder_build(SEXP sexp_builderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_builder(sexp_builderSEXP);
    rcpp_result_gen = Rcpp::wrap(_builder_build(sexp_builder));
    return rcpp_result_gen;
END_RCPP
}
// _simulation_run
void _simulation_run(SEXP sexp_simulation);
RcppExport SEXP _amsimr__simulation_run(SEXP sexp_simulationSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sexp_simulation(sexp_simulationSEXP);
    _simulation_run(sexp_simulation);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_amsimr__pheno_h2", (DL_FUNC) &_amsimr__pheno_h2, 0},
    {"_amsimr__pheno_comp_mean", (DL_FUNC) &_amsimr__pheno_comp_mean, 1},
    {"_amsimr__pheno_comp_var", (DL_FUNC) &_amsimr__pheno_comp_var, 1},
    {"_amsimr__pheno_comp_cor", (DL_FUNC) &_amsimr__pheno_comp_cor, 1},
    {"_amsimr__pheno_comp_xcor", (DL_FUNC) &_amsimr__pheno_comp_xcor, 1},
    {"_amsimr__pheno_latent_h2", (DL_FUNC) &_amsimr__pheno_latent_h2, 0},
    {"_amsimr__pheno_latent_comp_mean", (DL_FUNC) &_amsimr__pheno_latent_comp_mean, 1},
    {"_amsimr__pheno_latent_comp_var", (DL_FUNC) &_amsimr__pheno_latent_comp_var, 1},
    {"_amsimr__pheno_latent_comp_cor", (DL_FUNC) &_amsimr__pheno_latent_comp_cor, 1},
    {"_amsimr__pheno_latent_comp_xcor", (DL_FUNC) &_amsimr__pheno_latent_comp_xcor, 1},
    {"_amsimr__builder_new", (DL_FUNC) &_amsimr__builder_new, 0},
    {"_amsimr__builder_simulation", (DL_FUNC) &_amsimr__builder_simulation, 5},
    {"_amsimr__builder_genome", (DL_FUNC) &_amsimr__builder_genome, 5},
    {"_amsimr__builder_phenome", (DL_FUNC) &_amsimr__builder_phenome, 9},
    {"_amsimr__builder_mating", (DL_FUNC) &_amsimr__builder_mating, 6},
    {"_amsimr__builder_metrics", (DL_FUNC) &_amsimr__builder_metrics, 2},
    {"_amsimr__builder_build", (DL_FUNC) &_amsimr__builder_build, 1},
    {"_amsimr__simulation_run", (DL_FUNC) &_amsimr__simulation_run, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_amsimr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
